### ISSUE TITLE
Node.JS 0.12 and IO.js binaries ?

### ISSUE THREAD

**Issue by SomaticIT** [jorgeazevedo/node-sqlserver-unofficial#10]
Do you think it's possible to provide prebuilt binaries for Node.JS 0.12 and IO.js ?

**Comment by MattFromGer** [comment]
Second that! Node.JS 0.12 binaries would be great!

**Comment by Ebsy** [comment]
Would really like to see 0.12 binaries too!

**Comment by jastribl** [comment]
yes please

**Comment by sankargorthi** [comment]
:+1:

**Comment by daleroy1** [comment]
Any chance we could get precompiled binaries for the latest node.js?

**Comment by jcollum** [comment]
Same here. But 5 months with no response makes me think: don't hold your breath.

**Comment by tysjiang** [comment]
Actually, you can take a breath now.

The latest update is that Microsoft has finally tasked a team into maintaining the official node-sqlserver project (https://github.com/Azure/node-sqlserver).  They are now working on it.  Unfortunately, they do not release timelines so we don't know when the next version will be released.  

With that said, a wonderful contributor (TimelordUK) is filling the gaps in the meantime and has already produced a node-sqlserver that is compatible with node 12 (and soon node 4.0.0).  The repo is here with binaries and all: 
https://github.com/TimelordUK/node-sqlserver-v8

I've actually been using it and so far, so good.
-Tony

**Comment by paulbjensen** [comment]
Thanks for the update @tysjiang.
